#!/usr/bin/env pwsh
<#
.SYNOPSIS
Creates a GitHub issue (draft card) for an existing post/book/model file and
adds it to the Content Calendar project (#9) in the "To Be Published" column.
Stores the file path in the custom "Post File" TEXT project field (if it exists).
Social variants should be added to the issue body before or after creation.

USAGE:
  pwsh .github/scripts/New-DraftCard.ps1 -FilePath "_posts/2026-07-20-my-post.md"
  pwsh .github/scripts/New-DraftCard.ps1 -FilePath "_posts/2026-07-20-my-post.md" -PublishDate "2026-07-28"

REQUIRES:
  GH_TOKEN (or GITHUB_TOKEN) — repo scope (issues: write)
  GH_PROJECT_TOKEN           — PAT with 'project' scope (for Projects v2 GraphQL)
  gh CLI installed

PARAMETERS:
  -FilePath     Relative path to the content file in the repo (required).
                Examples: _posts/2026-07-20-my-post.md  _books/mindset.md
  -PublishDate  ISO date YYYY-MM-DD to pre-fill the project Publish Date field (optional).

SETUP: The project must have a TEXT field named "Post File" for the file path to be
stored as a searchable project column. Create it in GitHub Projects → Settings → Fields.
#>

param(
    [Parameter(Mandatory)]
    [string]$FilePath,

    [string]$PublishDate = ''
)
$ErrorActionPreference = 'Stop'

# Load local secrets if present (gitignored .env.ps1 in repo root)
$_envFile = Join-Path (Split-Path (Split-Path $PSScriptRoot)) '.env.ps1'
if (Test-Path $_envFile) { . $_envFile }

$REPO           = $env:GITHUB_REPOSITORY ?? 'renevanosnabrugge/culture-engineer'
$OWNER          = $REPO.Split('/')[0]
$PROJECT_NUMBER = 9

# Fail fast if project token is missing
if (-not ($env:GH_PROJECT_TOKEN ?? $env:GH_TOKEN ?? $env:GITHUB_TOKEN)) {
    Write-Error "No token found. Set `$env:GH_PROJECT_TOKEN` to a PAT with 'project' + 'repo' scopes.`nCreate one at: https://github.com/settings/tokens"
}

# ── helpers ───────────────────────────────────────────────────────────────────

function Invoke-GHGraphQL {
    param([string]$Query, [hashtable]$Variables = @{})
    $bodyBytes = [System.Text.Encoding]::UTF8.GetBytes(
        (@{ query = $Query; variables = $Variables } | ConvertTo-Json -Depth 15)
    )
    $token = $env:GH_PROJECT_TOKEN ?? $env:GH_TOKEN ?? $env:GITHUB_TOKEN
    $resp  = Invoke-RestMethod -Uri 'https://api.github.com/graphql' `
        -Method POST `
        -Headers @{
            Authorization  = "Bearer $token"
            'Content-Type' = 'application/json'
            'User-Agent'   = 'culture-engineer-bot'
        } `
        -Body $bodyBytes
    if ($resp.errors) {
        Write-Warning "GraphQL errors: $($resp.errors | ConvertTo-Json -Compress)"
    }
    return $resp
}

# ── 1. Validate file and read title from front matter ────────────────────────

if (-not (Test-Path $FilePath)) {
    Write-Error "File not found: $FilePath`nRun this script from the repository root."
}

$content = Get-Content $FilePath -Raw -Encoding UTF8
$title   = ''

if ($content -match '(?m)^title:\s*[''"]?(.+?)[''"]?\s*$') {
    $title = $Matches[1].Trim(" `"'")
}

if (-not $title) {
    # Derive from filename: strip YYYY-MM-DD- prefix and .md extension
    $leaf  = Split-Path $FilePath -Leaf
    $slug  = ($leaf -replace '^\d{4}-\d{2}-\d{2}-', '') -replace '\.md$', ''
    $title = (Get-Culture).TextInfo.ToTitleCase(($slug -replace '-', ' '))
}

Write-Host "Title : $title"
Write-Host "File  : $FilePath"

# ── 2. Build issue body ───────────────────────────────────────────────────────

$rawFileUrl = "https://github.com/$REPO/blob/main/$FilePath"

$publishDateComment = if ($PublishDate) { "`n<!-- publish-date: $PublishDate -->" } else { '' }
$metaPublishDate = if ($PublishDate) { $PublishDate } else { 'YYYY-MM-DD' }

$issueBody = @"
<!-- CONTENT CALENDAR METADATA
file: $FilePath
type: blog
publish-date: $metaPublishDate
image:
post-url:
-->
<!-- POST-FILE: $FilePath -->$publishDateComment

📄 **Post file:** [\`$FilePath\`]($rawFileUrl)

> Auto-generated by \`New-DraftCard.ps1\`.
> Set a **Publish Date** in the project board. The content scheduler
> will publish on that date and LinkedIn variants will be posted automatically.
> Edit the LinkedIn sections below to customize.

## LinkedIn — Variant 1 (Contrarian hook)

[Add LinkedIn Variant 1 text here]

---

## LinkedIn — Variant 2 (Story format)

[Add LinkedIn Variant 2 text here]

---

## LinkedIn — Variant 3 (Question format)

[Add LinkedIn Variant 3 text here]
"@

# ── 3. Create issue ───────────────────────────────────────────────────────────

Write-Host 'Creating GitHub issue...'
$issueUrl = & gh issue create `
    --repo  $REPO `
    --title "[Content] $title" `
    --body  $issueBody `
    --label 'content-calendar' `
    --label 'approve' 2>&1
if ($LASTEXITCODE -ne 0) { Write-Error "gh issue create failed: $issueUrl" }
$issueUrl   = $issueUrl.Trim()
$issueNumber = [int](($issueUrl -split '/')[-1])
$issue = [pscustomobject]@{ url = $issueUrl; number = $issueNumber }
Write-Host "Issue #$($issue.number) created: $($issue.url)"

# ── 4. Fetch project metadata ─────────────────────────────────────────────────

Write-Host "Fetching project #$PROJECT_NUMBER metadata..."
$projData = Invoke-GHGraphQL -Query @'
  query($owner: String!, $number: Int!) {
    user(login: $owner) {
      projectV2(number: $number) {
        id
        fields(first: 30) {
          nodes {
            ... on ProjectV2SingleSelectField { __typename id name options { id name } }
            ... on ProjectV2Field             { __typename id name dataType }
          }
        }
      }
    }
  }
'@ -Variables @{ owner = $OWNER; number = $PROJECT_NUMBER }

$proj      = $projData.data.user.projectV2
$projectId = $proj.id

$statusFieldId   = $null
$draftOptionId   = $null
$dateFieldId     = $null
$postFileFieldId = $null

foreach ($f in $proj.fields.nodes) {
    if (-not $f -or -not $f.name) { continue }
    $n = $f.name.ToLower()
    switch -Wildcard ($n) {
        'status' {
            $statusFieldId = $f.id
            $opt = $f.options | Where-Object { $_.name -match '(?i)to.?be' } | Select-Object -First 1
            if ($opt) { $draftOptionId = $opt.id }
        }
        { $_ -like '*publish*' -and $f.__typename -eq 'ProjectV2Field' -and $f.dataType -eq 'DATE' } {
            $dateFieldId = $f.id
        }
        { ($_ -like '*post*file*' -or $_ -like '*file*path*' -or $_ -eq 'post file' -or $_ -eq 'file') -and
          $f.__typename -eq 'ProjectV2Field' -and $f.dataType -eq 'TEXT' } {
            $postFileFieldId = $f.id
        }
    }
}

Write-Host "Project    : $projectId"
Write-Host "Status fld : $statusFieldId  (Draft option: $draftOptionId)"
Write-Host "Date field : $dateFieldId"
Write-Host "PostFile   : $(if ($postFileFieldId) { $postFileFieldId } else { '(not found — add a TEXT field named ''Post File'' in project settings)' })"

if (-not $projectId)  { Write-Error "Project #$PROJECT_NUMBER not found. Verify GH_PROJECT_TOKEN has 'project' scope." }
if (-not $statusFieldId) { Write-Error "No 'Status' field found in project." }
if (-not $draftOptionId) { Write-Error "No 'To Be Published' option found in Status field." }

# ── 5. Add issue to project via GraphQL (no gh CLI project scope needed) ──────

Write-Host 'Adding issue to project...'

# Get issue node ID
$issueNodeId = (Invoke-GHGraphQL -Query @'
  query($o: String!, $r: String!, $n: Int!) {
    repository(owner: $o, name: $r) { issue(number: $n) { id } }
  }
'@ -Variables @{ o = $OWNER; r = ($REPO.Split('/')[1]); n = $issue.number }).data.repository.issue.id

# Add to project
$addResult = Invoke-GHGraphQL -Query @'
  mutation($project: ID!, $content: ID!) {
    addProjectV2ItemById(input: { projectId: $project contentId: $content }) {
      item { id }
    }
  }
'@ -Variables @{ project = $projectId; content = $issueNodeId }

$itemId = $addResult.data.addProjectV2ItemById.item.id

if (-not $itemId) { Write-Error "Could not add issue #$($issue.number) to project. Check that GH_PROJECT_TOKEN has 'project' write scope." }
Write-Host "Item ID: $itemId"

# ── 6. Set project fields ─────────────────────────────────────────────────────

$setField = @'
  mutation($project: ID!, $item: ID!, $field: ID!, $value: ProjectV2FieldValue!) {
    updateProjectV2ItemFieldValue(input: {
      projectId: $project itemId: $item fieldId: $field value: $value
    }) { projectV2Item { id } }
  }
'@

# Status → Draft Posts
Invoke-GHGraphQL -Query $setField -Variables @{
    project = $projectId; item = $itemId
    field   = $statusFieldId
    value   = @{ singleSelectOptionId = $draftOptionId }
} | Out-Null
Write-Host "Status → To Be Published"

# Post File → file path
if ($postFileFieldId) {
    Invoke-GHGraphQL -Query $setField -Variables @{
        project = $projectId; item = $itemId
        field   = $postFileFieldId
        value   = @{ text = $FilePath }
    } | Out-Null
    Write-Host "Post File → $FilePath"
} else {
    Write-Warning "No 'Post File' TEXT field found. File path is stored only in the issue body."
}

# Publish Date (optional)
if ($PublishDate -and $dateFieldId) {
    Invoke-GHGraphQL -Query $setField -Variables @{
        project = $projectId; item = $itemId
        field   = $dateFieldId
        value   = @{ date = $PublishDate }
    } | Out-Null
    Write-Host "Publish Date → $PublishDate"
}

Write-Host ""
Write-Host "Done. Content card created: $($issue.url)"
Write-Host "Next: Set a Publish Date in the project. Content will be published and LinkedIn variants posted automatically."
